config/routes.rb
Rails.application.routes.draw do
  resources :registries do
    resources :enrollments, only: [:new, :create, :index]
    resources :participants, only: [:index,:new,:create]
  resources :coordinators, only: [:new, :create, :index]
  end

  get 'export_participants', to: 'participants#export'
  root 'registries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
  has_many :enrollments
  has_many :participants, through: :enrollments
  has_many :registries, through: :enrollments
  validates :email, presence: true, uniqueness: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :coordinator
  belongs_to :participant
  belongs_to :registry
  validates :participant, uniqueness: { scope: :registry, message: "has already been enrolled in this registry." }
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :enrollments
  has_many :coordinators, through: :enrollments
  has_many :registries, through: :enrollments
  validates :name, uniqueness: { scope: :registries, message: "has already been enrolled in this registry." }
end

app/models/registry.rb
class Registry < ApplicationRecord
  has_many :enrollments
  has_many :participants, through: :enrollments
  has_many :coordinators, through: :enrollments
  enum status: [:close, :open]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  def new
    @registry = Registry.find(params[:registry_id])
    @coordinator = Coordinator.new
  end

  def create
    @registry = Registry.find(params[:registry_id])
    @coordinator = @registry.coordinators.build(coordinator_params)
    
    if @coordinator.save(validate: false)
      redirect_to @registry, notice: 'Coordinator created successfully.'
    else
      render :new
    end
  end

  private

  def coordinator_params
    params.require(:coordinator).permit(:name, :email, :phone_number, registry_ids: [])
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_registry
  before_action :set_coordinator, only: [:new, :create]

  def new
    @enrollment = Enrollment.new
    @participants = Participant.all
  end

  def create
    @enrollment = @coordinator.enrollments.build(enrollment_params)
    if @enrollment.save
      redirect_to registry_enrollments_path(@registry), notice: "Participant was successfully enrolled."
    else
      @participants = Participant.all
      render :new
    end
  end

  def index
    @enrollments = @registry.enrollments.includes(:coordinator, :participant).order(:created_at)
    @enrollments_by_coordinator = @enrollments.group_by(&:coordinator)
  end

  private

  def set_registry
    @registry = Registry.find(params[:registry_id])
  end

  def set_coordinator
    @coordinator = Coordinator.find(params[:coordinator_id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:participant_id, :date_of_enrollment, :method_of_contact, :remarks)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def index
    @registry = Registry.find(params[:registry_id])
    @participants = @registry.participants.group_by(&:coordinator)
  end

  def export
    @coordinators = Coordinator.all
    respond_to do |format|
      format.csv { send_data participants_to_csv, filename: "participants.csv" }
    end
  end

   def new
    @registry = Registry.find(params[:registry_id])

    @participant = Participant.new
  end

  def create
    @participant = Participant.new(participant_params)
    if @participant.save(validate: false)
      redirect_to @participant, notice: 'Participant was successfully created.'
    else
      render :new
    end
  end

  private

  def participant_params
    params.require(:participant).permit(:name,:gender,:date_of_birth)
  end

  def participants_to_csv
    CSV.generate(headers: true) do |csv|
      csv << ["Name", "Gender", "Date of Birth", "Enrollment Date", "Method of Contact", "Remarks", "Coordinator"]
      @coordinators.each do |coordinator|
        coordinator.participants.each do |participant|
          csv << [participant.name, participant.gender, participant.date_of_birth, participant.enrollments.first.date_of_enrollment, participant.enrollments.first.method_of_contact, participant.enrollments.first.remarks, coordinator.name]
        end
      end
    end
  end
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  def index
    @registries = Registry.all
  end

  def show
  @registry = Registry.find(params[:id])
  @coordinators = @registry.coordinators
  @enrollments_by_coordinator = Enrollment.includes(:participant).where(registry_id: @registry.id).group_by(&:coordinator)
end


  def new
    @registry = Registry.new
  end

  def create
    @registry = Registry.new(registry_params)
    if @registry.save
      redirect_to @registry, notice: "Registry was successfully created."
    else
      render :new
    end
  end

  private

  def registry_params
    params.require(:registry).permit(:name, :location, :state, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/coordinators/index.html.erb
<h1>Coordinators</h1>
<ul>
  <% @coordinators.each do |coordinator| %>
    <li>
      <%= link_to coordinator.name, coordinator_path(coordinator) %>
      - <%= coordinator.email %>
      - <%= coordinator.phone_number %>
    </li>
  <% end %>
</ul>

app/views/coordinators/new.html.erb
<h1>New Coordinator</h1>

<%= form_with model: [@registry, @coordinator], url: registry_coordinators_path(@registry), local: true do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

<div class="field">
    <%= form.label :registry_ids, "Registries" %><br>
    <%= form.collection_check_boxes :registry_ids, Registry.all, :id, :name %>
  </div>
  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit "Create Coordinator" %>
  </div>
<% end %>

app/views/coordinators/show.html.erb
<h1><%= @coordinator.name %> Details</h1>
<p>Email: <%= @coordinator.email %></p>
<p>Phone Number: <%= @coordinator.phone_number %></p>

<h2>Enroll Participant</h2>
<%= link_to "Enroll Participant", new_registry_coordinator_enrollment_path(@registry, @coordinator) , class: 'btn btn-sm btn-primary' %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= form_with(model: [@registry, @coordinator, @enrollment], url: registry_enrollments_path(@registry, @coordinator), local: true) do |form| %>
  <div class="field">
    <%= form.label :participant_id %>
    <%= form.collection_select :participant_id, @participants, :id, :name %>
  </div>


  <div class="field">
    <%= form.label :date_of_enrollment %>
    <%= form.date_field :date_of_enrollment %>
  </div>

  <div class="field">
    <%= form.label :method_of_contact %>
    <%= form.select :method_of_contact, ["phone", "email"] %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks %>
  </div>

  <div class="actions">
    <%= form.submit "Enroll Participant" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParticipantTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participants/index.html.erb
<h1>Participants for <%= @registry.name %></h1>
<% @participants.each do |coordinator, participants| %>
  <h3><%= coordinator.name %></h3>
  <ul>
    <% participants.each do |participant| %>
      <li><%= participant.name %> - <%= participant.gender %> - <%= participant.date_of_birth %></li>
    <% end %>
  </ul>
<% end %>
<%= link_to "Export Participants", export_participants_path(format: :csv) %>

app/views/participants/new.html.erb
<%= form_with model: [@registry,  @participant], url: registry_participants_path(@registry), local: true do |form| %>

  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% @participant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registries/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
        <h3>Registries</h3>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Location</th>
              <th scope="col">State</th>
              <th scope="col">Status</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @registries.each do |registry| %>
              <tr>
                <th scope="row">1</th>
                <td><%= link_to registry.name, registry_path(registry) %></td>
                <td><%= registry.location %></td>
                <td><%= registry.status %></td>
                <td><%= registry.status %></td>
                <td>
                  <%= link_to 'View Participants', registry_participants_path(registry), class: 'btn btn-sm btn-primary' %>
                  <%= link_to"add coordinator",new_registry_coordinator_path(registry), class: 'btn btn-sm btn-secondary' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to"add the registry",new_registry_path, class: 'btn btn-sm btn-primary' %>
    </div>
  </div>
</div>

app/views/registries/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h3>New Registry</h3>
      <%= form_with model: @registry, url: registries_path, local: true do |form| %>

        <div class="mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :location, class: 'form-label' %>
          <%= form.text_field :location, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :state, class: 'form-label' %>
          <%= form.text_field :state, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.select :status, Registry.statuses.keys.map { |r| [r.humanize.capitalize, r] }, {}, class: 'form-select' %>
        </div>

        <div class="mb-3">
          <%= form.submit "Create Registry", class: 'btn btn-primary' %>
        </div>
       <% end %>
    </div>
  </div>
</div>

app/views/registries/show.html.erb
<h1><%= @registry.name %> Participants</h1>